Docker-Swarm-deployment/single-node/nginx-build/Dockerfile.alpine, Docker-Swarm-deployment/single-node/nginx-build/README.md, Docker-Swarm-deployment/single-node/resource-server/nginx/README.md, Docker-Swarm-deployment/single-node/resource-server/nginx/conf/error.conf, Docker-Swarm-deployment/single-node/resource-server/nginx/conf/rs.conf, Docker-Swarm-deployment/single-node/resource-server/nginx/rs-nginx.yml
- adding HSTS, content type, cache control
- adding strong cipher only
- clearing the server info - name
- adding custom error pages
- adding CORS
=> Hardening RS nginx config

Docker-Swarm-deployment/single-node/catalogue/nginx/cat-nginx.yml, Docker-Swarm-deployment/single-node/catalogue/nginx/conf/cat.conf, Docker-Swarm-deployment/single-node/catalogue/nginx/conf/error.conf, Docker-Swarm-deployment/single-node/catalogue/nginx/conf/middle-layer.conf
- adding HSTS, content type, cache control
- adding strong cipher only
- clearing the server info - name
- adding custom error pages
=> Hardeneing cat nginx config

K8s-deployment/Charts/latest-ingestion-pipeline/README.md, K8s-deployment/Charts/latest-ingestion-pipeline/example-aws-resource-values.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/example-azure-resource-yaml.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/example-secrets/secrets/attribute-mapping.json, K8s-deployment/Charts/latest-ingestion-pipeline/example-secrets/secrets/config.json, K8s-deployment/Charts/latest-ingestion-pipeline/install.sh, K8s-deployment/Charts/latest-ingestion-pipeline/templates/cache/deployment.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/templates/cache/hpa.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/templates/postgres/deployment.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/templates/postgres/hpa.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/templates/processor/deployment.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/templates/processor/hpa.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/templates/rabbitmq/deployment.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/templates/redis/deployment.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/templates/redis/hpa.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/values.yaml
- Updated to use a single config file and cli module parameter to deploy individual verticles.
- Separated values.yaml and resource-values.yaml
- Added installation script
- Added postgres and cache verticle templates
=> Helm chart updates: latest-ingestion-pipeline

Docker-Swarm-deployment/single-node/immudb/README.md, Docker-Swarm-deployment/single-node/immudb/docker/immudb-config-generator/Dockerfile, Docker-Swarm-deployment/single-node/immudb/docker/immudb-config-generator/immudb-config-generator.py, Docker-Swarm-deployment/single-node/immudb/immudb-config-generator.yml, Docker-Swarm-deployment/single-node/immudb/immudb-stack.yml
Update:
1. Image updated from 1.0.5 to 1.3.0
2. immudb-config-generator updated with changed in SQL syntax
3. Update in immudb-config-generator yaml file
=> Immudb version update to 1.3.0

K8s-deployment/K8s-cluster/Rancher/configs/aws/cluster.yaml, K8s-deployment/K8s-cluster/Rancher/configs/aws/iam-policies/K8s-worker-iam-policy.json, K8s-deployment/K8s-cluster/addons/storage/aws/README.md, K8s-deployment/K8s-cluster/addons/storage/aws/ebs-csi-storageclass.yaml
- added seperate ebs-csi storage class for now and updated readme with instructions, rke config file with needed changes.
-  update iam policy for worker nodes for ebs-csi and efs drivers
=> Adding ebs csi storage

K8s-deployment/Charts/immudb/Chart.yaml, K8s-deployment/Charts/immudb/README.md, K8s-deployment/Charts/immudb/example-aws-resource-values.yaml, K8s-deployment/Charts/immudb/install.sh, K8s-deployment/Charts/immudb/templates/stateful.yaml, K8s-deployment/Charts/immudb/values.yaml
- add standard labels and match labels (similar to postgres chart)
- increment chart version from 0.1.3 to 0.1.4
(Need to define policy on chart versioning)
=> Fixes: Helm immudb update

Docker-Swarm-deployment/single-node/databroker/databroker-stack.yaml
Update:
rabbitmq -->3.8.11 --> 3.10.5
=> RabbitMQ version update to 3.10.5

Docker-Swarm-deployment/single-node/keycloak/README.md, Docker-Swarm-deployment/single-node/keycloak/docker/Dockerfile, Docker-Swarm-deployment/single-node/keycloak/keycloak-stack.yaml
Updates:
1. Updates in stack files
2. image version from 14.0.0 to 18.0.1
3. Updates in Dockerfile
=> Swarm: Keycloak version update to 18.0.2

K8s-deployment/Charts/redis/README.md, K8s-deployment/Charts/redis/autoscale-cron.yaml, K8s-deployment/Charts/redis/docker/redis-autoscaler/Dockerfile, K8s-deployment/Charts/redis/docker/redis-autoscaler/docker-compose.yml, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/.bitnami_components.json, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libbitnami.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libcomponent.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libfile.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libfs.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libnet.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libos.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libservice.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libwebserver.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/rootfs/opt/bitnami/scripts/libredis.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/rootfs/opt/bitnami/scripts/redis-cluster-env.sh, K8s-deployment/Charts/redis/docker/redis-rejson/Dockerfile, K8s-deployment/Charts/redis/install.sh, K8s-deployment/Charts/redis/redis-autoscaler.sh, K8s-deployment/Charts/redis/redis.conf, K8s-deployment/Charts/redis/values.yaml, K8s-deployment/databroker/statefulset.yaml
- Redis updated to 7.0.2
- Rejson updated to 2.0.9
- RMQ updated to 3.10.5
- Added tcpKeepAlive for rmq
=> K8s software-update: RabbitMQ and REDIS

K8s-deployment/Charts/redis/README.md, K8s-deployment/Charts/redis/autoscale-cron.yaml, K8s-deployment/Charts/redis/docker/redis-autoscaler/Dockerfile, K8s-deployment/Charts/redis/docker/redis-autoscaler/docker-compose.yml, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/.bitnami_components.json, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libbitnami.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libcomponent.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libfile.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libfs.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libnet.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libos.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libservice.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/prebuildfs/opt/bitnami/scripts/libwebserver.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/rootfs/opt/bitnami/scripts/libredis.sh, K8s-deployment/Charts/redis/docker/redis-autoscaler/rootfs/opt/bitnami/scripts/redis-cluster-env.sh, K8s-deployment/Charts/redis/docker/redis-rejson/Dockerfile, K8s-deployment/Charts/redis/install.sh, K8s-deployment/Charts/redis/redis-autoscaler.sh, K8s-deployment/Charts/redis/redis.conf, K8s-deployment/Charts/redis/values.yaml, K8s-deployment/databroker/statefulset.yaml
- Redis updated to 7.0.2
- Rejson updated to 2.0.9
- RMQ updated to 3.10.5
- Added tcpKeepAlive for rmq
- Added bitnami full index repo
- Updated redis autoscaler
=> K8s software-update: RabbitMQ and REDIS [for 3.5.0]

Docker-Swarm-deployment/single-node/postgres/init-scripts/db-user-creation.sh
- include creation of db in swarm postgres init script
- rs schema script creation script also included creation of rs db https://github.com/datakaveri/iudx-deployment/pull/163/commits/7f809f21ad9ba5628f50c68acc19dfd79590a291 , hence this became a bug @pranavv0 @THARAK-RAM1
=> 3.5.0:- correct postgres init script

Docker-Swarm-deployment/single-node/postgres/README.md
- use proper branch for rs, auth schema migration
- correct psql dump in notes
=> 3.5.0: corrections to swarm postgres -II

Docker-Swarm-deployment/single-node/resource-server/example-secrets/secrets/config.json, K8s-deployment/Charts/resource-server/example-secrets/secrets/config.json
- correct some rs config options -``meteringDatabaseTableName``, ``meteringPoolSize``,``databaseIp``.
=> 3.5.0:- corrections swarm-K8s docs update

K8s-deployment/Charts/postgresql/README.md, K8s-deployment/Charts/postgresql/init-scripts/db-user-creation.sh, K8s-deployment/Charts/postgresql/install.sh, K8s-deployment/Charts/postgresql/psql-async-values.yaml
Updates:
1. image version from 11.14.0 to 14.4.0
2. Updates in Stack files
3. Updates in README
4. Enable TCP keepalive at Postgres
5. removed auth_db_name from init-script
=> K8s: Postgres Version Update

K8s-deployment/K8s-cluster/addons/ingress-controller/ingress-nginx/nginx-values.yaml, K8s-deployment/K8s-cluster/addons/ingress-controller/install.sh, K8s-deployment/K8s-cluster/addons/ingress-controller/memcached/memcached-values.yaml, K8s-deployment/K8s-cluster/addons/ingress-controller/tests/connectivity-test.sh, K8s-deployment/K8s-cluster/addons/ingress-controller/tests/example-ingress-connections.yaml, K8s-deployment/K8s-cluster/addons/ingress-controller/tests/example-ingress-grl.yaml, K8s-deployment/K8s-cluster/addons/ingress-controller/tests/example-ingress-rps.yaml
Updates:
1. Ingress-nginx updated from 1.0.0 to 1.3.0
2. memcache updates from 1.6.10 to 1.6.17
=> Ingress-nginx and Memcached Version Update

K8s-deployment/Charts/zookeeper/install.sh, K8s-deployment/Charts/zookeeper/zookeeper-values.yaml
Used bitnami full index
Added dataLogDir: "/bitnami/zookeeper/dataLog"
Changed replicas count from 1 to 3
=> K8s: Zookeeper update

Docker-Swarm-deployment/single-node/auth/auth-stack.yaml, Docker-Swarm-deployment/single-node/catalogue/cat-stack.yaml, Docker-Swarm-deployment/single-node/data-ingestion-server/di-stack.yaml, Docker-Swarm-deployment/single-node/elk/example-database-stack.resources.yaml, Docker-Swarm-deployment/single-node/file-server/file-server-stack.yaml, Docker-Swarm-deployment/single-node/gis/gis-stack.yaml, Docker-Swarm-deployment/single-node/lip/lip-stack.yaml, Docker-Swarm-deployment/single-node/resource-server/rs-stack.yaml, K8s-deployment/Charts/auth-server/Chart.yaml, K8s-deployment/Charts/auth-server/values.yaml, K8s-deployment/Charts/catalogue/Chart.yaml, K8s-deployment/Charts/catalogue/values.yaml, K8s-deployment/Charts/data-ingestion/Chart.yaml, K8s-deployment/Charts/data-ingestion/values.yaml, K8s-deployment/Charts/elk/elasticsearch/es-values.yml, K8s-deployment/Charts/elk/elasticsearch/java-net.options, K8s-deployment/Charts/elk/es-install.sh, K8s-deployment/Charts/file-server/Chart.yaml, K8s-deployment/Charts/file-server/values.yaml, K8s-deployment/Charts/gis-interface/Chart.yaml, K8s-deployment/Charts/gis-interface/values.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/Chart.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/values.yaml, K8s-deployment/Charts/resource-server/Chart.yaml, K8s-deployment/Charts/resource-server/values.yaml
- also patch elastic to make tcp keepalive work 
- Refer: 
1. https://github.com/elastic/elasticsearch/issues/88897
2. Temporary fix: https://github.com/elastic/elasticsearch/issues/88897#issuecomment-1198292504
=> K8s/Swarm: Upgrade to latest 4.0.0 api servers

Docker-Swarm-deployment/single-node/immudb/immudb-stack.yaml, K8s-deployment/Charts/immudb/README.md, K8s-deployment/Charts/immudb/immudb-audit.yaml, K8s-deployment/Charts/immudb/values.yaml
Upgrades immudb to 1.4.1
Changes in stack file
Changes in Values.yaml
Changes in immudb-audit.yaml
Changes in Chart Readme
=> upgrade immude to 1.4.1

K8s-deployment/Charts/elk/README.md, K8s-deployment/Charts/elk/create-secrets.sh, K8s-deployment/Charts/elk/elasticsearch/es-values.yml, K8s-deployment/Charts/elk/example-secrets/secrets/passwords/s3-credentials, K8s-deployment/Charts/elk/example-secrets/secrets/passwords/snapshot-credentials
=> [4.0.0] Update for azure snapshot configuration

K8s-deployment/Charts/elk/README.md, K8s-deployment/Charts/elk/create-secrets.sh, K8s-deployment/Charts/elk/elasticsearch/es-values.yml, K8s-deployment/Charts/elk/example-secrets/secrets/passwords/s3-credentials, K8s-deployment/Charts/elk/example-secrets/secrets/passwords/snapshot-credentials
(cherry picked from commit 0f32b27ec396dd0f42e7fdad43767a2bcfcc8610)
=> Update for azure snapshot configuration

K8s-deployment/Charts/resource-server/example-aws-resource-values.yaml, K8s-deployment/Charts/resource-server/example-azure-resource-values.yaml
- Updated sample resource values files to have the enable verticles flag.
(cherry picked from commit c129087d17d99814238a8dee4bc9d490c2bd146f)
=> [4.0.0] Updated RS sample resource values

K8s-deployment/Charts/elk/elasticsearch/es-autoscaler.sh, K8s-deployment/Charts/elk/elasticsearch/generate-certs.sh, K8s-deployment/Charts/elk/logstash/logstash-config.yaml, K8s-deployment/Charts/postgresql/psql-async-values.yaml, K8s-deployment/Charts/redis/values.yaml
- es cert generation script permission issue fix
- logstash pipeline set to passive for resolving RMQ user permission issue. 
- fix psql values config indentation
- redis: removed runAsNonRoot as it was causing the init container to also run as non-root which caused it to fail.
=> [4.0.0] Updates and Fixes

K8s-deployment/Charts/elk/elasticsearch/es-autoscaler.sh, K8s-deployment/Charts/elk/elasticsearch/generate-certs.sh, K8s-deployment/Charts/elk/logstash/logstash-config.yaml, K8s-deployment/Charts/postgresql/psql-async-values.yaml, K8s-deployment/Charts/redis/values.yaml
- es cert generation script permission issue fix
- logstash pipeline set to passive for resolving RMQ user permission issue. 
- fix psql values config indentation
- redis: removed runAsNonRoot as it was causing the init container to also run as non-root which caused it to fail.
- Curl requests to ES were failing due to special characters in the ES_PASSWORD string.
added step to first URLencode the password and then use that in the curl.
- porting to master from #227
=> Master updates fixes

Docker-Swarm-deployment/single-node/databroker/create-secrets.sh, Docker-Swarm-deployment/single-node/databroker/example-secrets/secrets/init-config.json, Docker-Swarm-deployment/single-node/databroker/rmq-init-setup.yaml, K8s-deployment/Charts/databroker/create-secrets.sh, K8s-deployment/Charts/databroker/example-secrets/secrets/init-config.json
- Add rs-proxy & adapter, rmq init-config changes
=> 4.0.0: Rmq changes 

K8s-deployment/K8s-cluster/addons/cluster-autoscaler/rancher/.gitignore, K8s-deployment/K8s-cluster/addons/cluster-autoscaler/rancher/README.md, K8s-deployment/K8s-cluster/addons/cluster-autoscaler/rancher/config.yaml, K8s-deployment/K8s-cluster/addons/cluster-autoscaler/rancher/example-resource-values.yaml, K8s-deployment/K8s-cluster/addons/cluster-autoscaler/rancher/values.yaml, K8s-deployment/K8s-cluster/addons/storage/aws/README.md, K8s-deployment/K8s-cluster/addons/storage/aws/ebs-csi-storageclass.yaml
- Added cluster-autoscaler for rancher provisioner, which uses [helm chart](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler) for installation.
- Updated ebs storage class to provision encrypted volumes.
=> RKE2 K8s changes in addons

K8s-deployment/K8s-cluster/addons/velero/aws/README.md, K8s-deployment/K8s-cluster/addons/velero/aws/velero-change-aws-az.sh
- Added bash script to update aws az in velero backed up files on s3
- Updated README
=> [K8s] [Velero] Migrate persistent volumes across aws availability zone

Docker-Swarm-deployment/single-node/lip/tests/latest-ingestion-pipeline-test.py, Docker-Swarm-deployment/single-node/lip/tests/requirements.txt
1. Update in latest-ingestion-pipeline-test.py
2. Update in requirements.txt
=> updated lip test code

Docker-Swarm-deployment/single-node/catalogue/example-secrets/secrets/config.json, Docker-Swarm-deployment/single-node/data-ingestion-server/di-stack.yaml, Docker-Swarm-deployment/single-node/resource-server/rs-stack.yaml, K8s-deployment/Charts/catalogue/example-secrets/secrets/config.json, K8s-deployment/Charts/data-ingestion/Chart.yaml, K8s-deployment/Charts/data-ingestion/example-aws-resource-values.yaml, K8s-deployment/Charts/data-ingestion/values.yaml, K8s-deployment/Charts/resource-server/Chart.yaml, K8s-deployment/Charts/resource-server/values.yaml
- upgrade di, correct cat nlp config
=> Upgrade API servers to 4.5.0

Docker-Swarm-deployment/single-node/resource-server/rs-stack.yaml, K8s-deployment/Charts/resource-server/values.yaml
=> 4 5 0: 4.5.0 post release fixes II

Docker-Swarm-deployment/single-node/adv-mon-stack/ams-stack.yaml, Docker-Swarm-deployment/single-node/adv-mon-stack/example-secrets/secrets/adv-mon-stack-conf.json, K8s-deployment/adv-monstack/adv-monstack.yaml, K8s-deployment/adv-monstack/example-secrets/secrets/adv-mon-stack-conf.json, docker/adv-mon-stack/README.md, docker/adv-mon-stack/src/aa.txt, docker/adv-mon-stack/src/adv-monstack.py
1. Updated with new images
2. New images pushed
3. changes in apis
=> Adv monstack fix

Docker-Swarm-deployment/single-node/adv-mon-stack/ams-stack.yaml, Docker-Swarm-deployment/single-node/adv-mon-stack/example-secrets/secrets/adv-mon-stack-conf.json, K8s-deployment/adv-monstack/adv-monstack.yaml, K8s-deployment/adv-monstack/example-secrets/secrets/adv-mon-stack-conf.json, docker/adv-mon-stack/README.md, docker/adv-mon-stack/src/aa.txt, docker/adv-mon-stack/src/adv-monstack.py
=> 4.5.0 adv fix

Docker-Swarm-deployment/single-node/immudb/example-secrets/secrets/config.json, Docker-Swarm-deployment/single-node/immudb/immudb-config-generator.yaml, K8s-deployment/Charts/immudb/README.md, K8s-deployment/Charts/immudb/example-secrets/secrets/config.json, K8s-deployment/Charts/immudb/values.yaml, docker/immudb/immudb-config-generator/README.md, docker/immudb/immudb-config-generator/src/immudb-config-generator.py
Require changes for adding default username and password
=> script changes

Docker-Swarm-deployment/single-node/auth/example-secrets/secrets/config.json, Docker-Swarm-deployment/single-node/elk/README.md, Docker-Swarm-deployment/single-node/elk/database-stack.yaml, Docker-Swarm-deployment/single-node/elk/example-database-stack.resources.yaml, Docker-Swarm-deployment/single-node/elk/kibana/kibana.yaml, K8s-deployment/Charts/auth-server/example-secrets/secrets/config.json
- update to configure kibana public base url from kibana.yaml
=> [4.5.0] Update to configure Kibana publicBaseURL from kibana.yaml

Docker-Swarm-deployment/single-node/immudb/example-secrets/secrets/config.json, Docker-Swarm-deployment/single-node/immudb/immudb-config-generator.yaml, K8s-deployment/Charts/immudb/README.md, K8s-deployment/Charts/immudb/example-secrets/secrets/config.json, K8s-deployment/Charts/immudb/values.yaml, docker/immudb/immudb-config-generator/README.md, docker/immudb/immudb-config-generator/src/immudb-config-generator.py
backport of https://github.com/datakaveri/iudx-deployment/pull/533
=> script chnages

Docker-Swarm-deployment/single-node/nginx/README.md, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/auth.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/cat.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/cos.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/default.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/di.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/fs.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/grafana.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/keycloak.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/kibana.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/rs-proxy.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/rs.conf, Docker-Swarm-deployment/single-node/nginx/example-nginx-stack.resources.yaml, Docker-Swarm-deployment/single-node/nginx/nginx-stack.yaml
- Separated rs from cos config in nginx
=> [4.5.0] Nginx COS and RS config update

Docker-Swarm-deployment/single-node/nginx/example-configs/conf/nginx.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/onboarding.conf, Docker-Swarm-deployment/single-node/nginx/nginx-stack.yaml, Docker-Swarm-deployment/single-node/onboarding-server/README.md, Docker-Swarm-deployment/single-node/onboarding-server/example-onboarding-server-stack.custom.yaml, Docker-Swarm-deployment/single-node/onboarding-server/example-onboarding-server-stack.resources.yaml, Docker-Swarm-deployment/single-node/onboarding-server/example-secrets/secrets/.onboarding.env, Docker-Swarm-deployment/single-node/onboarding-server/example-secrets/secrets/config.json, Docker-Swarm-deployment/single-node/onboarding-server/onboarding-server-stack.yaml
added deployment files for onboarding server
=> Onboarding server docker-swarm deployment files

Docker-Swarm-deployment/single-node/keycloak/keycloak-stack.yaml, K8s-deployment/Charts/keycloak/install.sh, K8s-deployment/Charts/keycloak/values.yaml
=> Keycloak v22.0.1 update

Docker-Swarm-deployment/single-node/immudb/create-secrets.sh, Docker-Swarm-deployment/single-node/immudb/example-secrets/secrets/config.json, Docker-Swarm-deployment/single-node/immudb/immudb-config-generator.yaml, K8s-deployment/Charts/immudb/create-secrets.sh, K8s-deployment/Charts/immudb/example-secrets/secrets/config.json, K8s-deployment/Charts/immudb/values.yaml, docker/immudb/immudb-config-generator/src/immudb-config-generator.py
=> immudb: code changes

Docker-Swarm-deployment/single-node/acl-apd/README.md, Docker-Swarm-deployment/single-node/acl-apd/acl-apd-stack.yaml, Docker-Swarm-deployment/single-node/acl-apd/example-acl-apd-stack.custom.yaml, Docker-Swarm-deployment/single-node/acl-apd/example-acl-apd-stack.resources.yaml, Docker-Swarm-deployment/single-node/acl-apd/example-secrets/secrets/.apd.env, Docker-Swarm-deployment/single-node/acl-apd/example-secrets/secrets/config.json, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/acl-apd.conf, Docker-Swarm-deployment/single-node/nginx/example-configs/conf/nginx.conf, Docker-Swarm-deployment/single-node/nginx/nginx-stack.yaml
=> Docker: acl-apd deployment

K8s-deployment/Charts/acl-apd/values.yaml
=> K8s: helm acl-apd 

K8s-deployment/Charts/latest-ingestion-pipeline/values.yaml
correction in values.yaml command
=> K8s: corrected values.yaml

K8s-deployment/Charts/onboarding-server/templates/ingestion/deployment.yaml, K8s-deployment/Charts/onboarding-server/templates/resourceServer/deployment.yaml, K8s-deployment/Charts/onboarding-server/templates/resourceServer/hpa.yaml, K8s-deployment/Charts/onboarding-server/values.yaml
- correct template helpers
- K8s resource name needs to be small case alphanumeric. -
=> Fixes onboarding helm chart

Docker-Swarm-deployment/single-node/monitoring-stack/README.md
Added a step to create a temporary directory in the Mon Stack README.md file.
=> Modified Mon Stack README.md File

Docker-Swarm-deployment/single-node/zookeeper/zookeeper-stack.yaml
Modified updated version of zookeeper, tested and verified deployment locally.
=> [Docker-swarm] Zookeeper Software Update

Docker-Swarm-deployment/single-node/redis/redis-rejson-stack.yaml, docker/redis/README.md, docker/redis/redis-rejson/Dockerfile
This pull request implements the deployment of Redis in Docker Swarm. Tested it by log in to the container and executed the commands in Redis. Added essential files such as redis-rejson-stack.yaml. Updated Redis image version from redis-rejson:7.0.2-2.0.9 to redis-rejson:7.2.4-2.6.8
=> [Docker-swarm] Redis Software Update

Docker-Swarm-deployment/single-node/keycloak/keycloak-stack.yaml, docker/keycloak/Dockerfile, docker/keycloak/README.md
This pull request implements the deployment of Keycloak in Docker Swarm. Tested it by checking the logs and service is running. Added essential file keycloak-stack.yaml. Updated Keycloak image version from keycloak:21.1.1 to keycloak:23.0.4
=> [Docker-swarm] Keycloak Software Update

K8s-deployment/Charts/zookeeper/install.sh, K8s-deployment/Charts/zookeeper/zookeeper-values.yaml
- Zookeeper version upgraded to latest stable version 3.9.1-debian-11-r4
=> [K8s][Helm] Zookeeper Software Update

docs/immudb-setup/README.md
- Added the setup steps for immuclient 
-  contributed by @abhi4578
=> Adding immudb setup

.gitignore, docs/immudb-setup/README.md
=> Refactor README.md

K8s-deployment/Charts/redis/install.sh, K8s-deployment/Charts/redis/values.yaml, docker/redis/redis-cluster-rejson/Dockerfile
This pull request implements the deployment of Redis in Kubernetes using a Helm chart. Thoroughly tested for Redis by checking the logs and pods running. Added essential files such as install.sh, values.yaml. Updated Redis image version from redis-rejson:7.0.2-2.0.9 to redis-rejson:7.2.4-2.6.8
=> [K8s][Helm] Redis Software Update

K8s-deployment/Charts/keycloak/install.sh, K8s-deployment/Charts/keycloak/values.yaml
This pull request implements the deployment of Keycloak in Kubernetes using a Helm chart. Thoroughly tested for Keycloak by checking the logs and pods running. Added essential files such as install.sh and values.yaml. Updated Keycloak image version from keycloak:21.1.1-1 to keycloak:23.0.4-debian-11-r1-t-1
=> [K8s][Helm] Keycloak Software Update

K8s-deployment/misc/K8s-ServersRestart-Script/K8s-API-Servers-restart.sh, K8s-deployment/misc/K8s-ServersRestart-Script/README.md, K8s-deployment/misc/K8s-ServersRestart-Script/config.json
Script to restart all API servers based on K8s in staging
=> [K8s] API Servers Restart Script

K8s-deployment/Charts/auditing-server/example-aws-resource-values.yaml, K8s-deployment/Charts/auditing-server/example-azure-resource-values.yaml
- updated resource values files to add cache verticle
=> [K8s] auditing helm update

Docker-Swarm-deployment/single-node/databroker/create-secrets.sh, Docker-Swarm-deployment/single-node/databroker/example-secrets/secrets/init-config.json, Docker-Swarm-deployment/single-node/databroker/rmq-init-setup.yaml, K8s-deployment/Charts/databroker/create-secrets.sh, K8s-deployment/Charts/databroker/example-secrets/secrets/init-config.json
added extra queue `subscriptions-monitoring`.
=> update in init-config RMQ for 5.5.0

Docker-Swarm-deployment/single-node/nginx/example-configs/conf/cos.conf
- Combined all cat routings
- added /stac
=> [Docker Swarm] Cos routing update

K8s-deployment/Charts/rs-proxy/example-aws-resource-values.yaml, K8s-deployment/Charts/rs-proxy/example-azure-resource-values.yaml, K8s-deployment/Charts/rs-proxy/example-secrets/secrets/config.json, K8s-deployment/Charts/rs-proxy/install.sh, K8s-deployment/Charts/rs-proxy/templates/consentlog/deployment.yaml, K8s-deployment/Charts/rs-proxy/templates/consentlog/hpa.yaml, K8s-deployment/Charts/rs-proxy/values.yaml
Added ConsentLoggingVerticle with udpated helm Charts
=> [K8s] rs-proxy Helm Update

Docker-Swarm-deployment/single-node/acl-apd/acl-apd-stack.yaml, Docker-Swarm-deployment/single-node/auditing-server/auditing-stack.yaml, Docker-Swarm-deployment/single-node/auth/auth-stack.yaml, Docker-Swarm-deployment/single-node/catalogue/cat-stack.yaml, Docker-Swarm-deployment/single-node/consent-validator/consent-stack.yaml, Docker-Swarm-deployment/single-node/data-ingestion-server/di-stack.yaml, Docker-Swarm-deployment/single-node/file-server/file-server-stack.yaml, Docker-Swarm-deployment/single-node/gis/gis-stack.yaml, Docker-Swarm-deployment/single-node/lip/lip-stack.yaml, Docker-Swarm-deployment/single-node/ogc-rs/ogc-rs-stack.yaml, Docker-Swarm-deployment/single-node/onboarding-server/onboarding-server-stack.yaml, Docker-Swarm-deployment/single-node/resource-server/rs-stack.yaml, Docker-Swarm-deployment/single-node/rs-proxy/rs-proxy-stack.yaml, K8s-deployment/Charts/acl-apd/values.yaml, K8s-deployment/Charts/auditing-server/values.yaml, K8s-deployment/Charts/auth-server/values.yaml, K8s-deployment/Charts/catalogue/values.yaml, K8s-deployment/Charts/data-ingestion/values.yaml, K8s-deployment/Charts/dmp-apd/values.yaml, K8s-deployment/Charts/file-server/values.yaml, K8s-deployment/Charts/geo-server/values.yaml, K8s-deployment/Charts/gis-interface/values.yaml, K8s-deployment/Charts/latest-ingestion-pipeline/values.yaml, K8s-deployment/Charts/onboarding-server/values.yaml, K8s-deployment/Charts/resource-server/values.yaml, K8s-deployment/Charts/rs-proxy/values.yaml, K8s-deployment/adv-monstack/adv-monstack.yaml
What this PR include?
- Updated Docker deployment images
- Updated K8s deployment images
=> [ImageUpdate] Update Docker & K8s depl images

Docker-Swarm-deployment/single-node/elk/account-generator.yaml, docker/elasticsearch/account-generator/src/account-creation.py
- added create_user call in script and pushed account generator image with tag 1.0.1
- used 1.0.1 account generator image with account generator stack
=> Fixed account generation script of elastic search

docker/keycloak/src/cbn_theme/login/login.ftl
Removed the icon for the password input field
=> FIX: Removed the password eye icon

K8s-deployment/Charts/acl-apd/values.yaml, K8s-deployment/Charts/catalogue/values.yaml, K8s-deployment/Charts/dmp-apd/templates/service.yaml, K8s-deployment/Charts/dmp-apd/values.yaml, K8s-deployment/Charts/onboarding-server/values.yaml
- Fixed incorrect service name references
- added `--isClustered` flag for both apd servers
=> [K8s][5.6.0] Helm service fixes

K8s-deployment/Charts/postgresql/install.sh, K8s-deployment/Charts/postgresql/pg_upgrade/README.md, K8s-deployment/Charts/postgresql/psql-async-values.yaml, docker/postgres/pg_upgrade/k8s/Dockerfile, docker/postgres/pg_upgrade/k8s/README.md
- updated the install.sh 
- added pg_upgrade folder and readme.md 
- added Dockerfile for pg_upgrade
=> [K8s][Helm]Postgres Software Update

K8s-deployment/Charts/zookeeper/install.sh, K8s-deployment/Charts/zookeeper/zookeeper-values.yaml
This pull request includes the following:
- Updated the image version from 3.9.1-debian-11-r3 to 3.9.3-debian-12-r3
- Updated install.sh script
- Updated zookeeper-values.yaml file
=>  [K8s][Helm] Zookeeper Software Update

K8s-deployment/Charts/keycloak/README.md, K8s-deployment/Charts/keycloak/values.yaml
=> [Keycloak]: K8s software upgrade to 26.2.3

Docker-Swarm-deployment/single-node/elk/database-stack.yaml, Docker-Swarm-deployment/single-node/elk/elasticsearch/account-generator-config.json, K8s-deployment/Charts/elk/elasticsearch/es-values.yml, K8s-deployment/Charts/elk/elasticsearch/generate-certs.sh, K8s-deployment/Charts/elk/es-install.sh, K8s-deployment/Charts/elk/generate-keystore.sh, K8s-deployment/Charts/elk/kibana-install.sh, K8s-deployment/Charts/elk/kibana/kibana-values.yml, K8s-deployment/Charts/elk/logstash-install.sh, K8s-deployment/Charts/elk/logstash/ls-values.yml
- Upgrade elk values to 8.17.3-debian-12-r0
=> [ELK]: K8s software upgrade to 8.17.3-debian-12-r0

docker/keycloak/Dockerfile-v23, docker/keycloak/Dockerfile-v26, docker/keycloak/Jenkinsfile
Created Jenkins file and Dockerfiles for the Keycloak pipeline.
=> [Jenkins CI] [Keycloak] [DI-34] created Jenkins Pipeline for Keycloak(v23 & v26).

docker/mon-stack/grafana/conf/dashboards/analytics/analytics-components-logs.json, docker/mon-stack/grafana/conf/dashboards/analytics/clickhouse-cluster.json, docker/mon-stack/grafana/conf/dashboards/analytics/flink-taskmanger-metrics.json, docker/mon-stack/grafana/conf/dashboards/analytics/minio-bucket-dashboard.json, docker/mon-stack/grafana/conf/dashboards/analytics/minio-metrics.json, docker/mon-stack/grafana/conf/dashboards/blackbox/blackbox-exporter.json, docker/mon-stack/grafana/conf/dashboards/blackbox/summary-blackbox-exporter-httpProber.json, docker/mon-stack/grafana/conf/dashboards/servers/summary-all-nodes.json, docker/mon-stack/grafana/conf/dashboards/servers/summary-critical-components.json, docker/mon-stack/grafana/conf/dashboards/servers/system-logs.json, docker/mon-stack/grafana/conf/dashboards/software-components/rabbitmq-overview.json
PR Includes:
1. analytics componets dashboards(clickhouse,minio,flink,analytic component logs)
2. servers dashboards (summary of all nodes,system logs ,critical components)
3. blackbox dashboards (summary , HttpProbe overview)
4. software-components dashboard (RabbitMQ)
=> [Grafana] dashboards

Docker-Swarm-deployment/single-node/elk/database-stack.yaml, K8s-deployment/Charts/elk/elasticsearch/es-autoscaler.sh, K8s-deployment/Charts/elk/elasticsearch/es-values.yml, K8s-deployment/Charts/elk/elasticsearch/generate-certs.sh, K8s-deployment/Charts/elk/generate-keystore.sh, K8s-deployment/Charts/elk/kibana/kibana-values.yml, K8s-deployment/Charts/elk/logstash/ls-values.yml
Updated ES, Kibana, and Logstash image versions to the  latest rolling version of Bitnami images
=>  [ELK] update fixes: Updated ES, Kibana, and Logstash image versions to the  latest rolling version 

Docker-Swarm-deployment/single-node/postgres/pg_upgrade/README.md, Docker-Swarm-deployment/single-node/postgres/postgres-stack.yaml, docker/postgres/pg_upgrade/docker-swarm/Dockerfile, docker/postgres/pg_upgrade/docker-swarm/README.MD
- Added README.md for pg_upgrade under postgresql repo
- Created Dockerfile and README.md for pg_upgrade
=> [Docker-swarm] Postgre upgraded to 17.4.0
